### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by LqNoob** [yandex-research/distill-nf#1]
Hi, @dbaranchuk. Thank you for your great work.
After reading this paper 'Distilling the Knowledge from Conditional Normalizing Flows', I have a questions here.

In this article, only super-resolution images and speech synthesis are done. Why not super-resolution and sample generation for both data types(image and speech)? Is it because the SRFlow model only processes images, while WaveGlow model only does speech synthesis?

Thank you.

**Comment by dbaranchuk** [comment]
Hi,

> Is it because the SRFlow model only processes images, while WaveGlow model only does speech synthesis?

Yes, SRFlow is specifically designed for image super-resolution, while WaveGlow is for speech synthesis.

**Comment by LqNoob** [comment]
Hi, @dbaranchuk. 
Thank you for your kindly reply. It is very helpful.
